name: Node.js script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Run script
        run: node scrapper.js
      - name: Push changes
        uses: actions/github-script@v3
        with:
          github_token: ${{ secrets.TOKEN_PUSH }}
        env:
          GITHUB_REPOSITORY: ${{ secrets.PUSH_REPOSITORY }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add gameNames.json
          git commit -m "Add game names"
          git push origin master

#name: Node.js script

#on:
#schedule:
# - cron: '0 0 * * *'
