name: Node.js script

on:
  schedule:
    - cron: '40 4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Run script
        run: node scrapper.js
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: gameNames.json
          path: gameNames.json
      - name: Push artifact
        uses: peter-evans/github-push-action@v3
        with:
          github_token: ${{ secrets.TOKEN_PUSH }}
